name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 2221
          script: |
            cd ~/Deteksi-lahan-Pertanian
            git pull origin main
            if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
            pm2 stop Deteksi-lahan || true
            pm2 delete Deteksi-lahan || true
            pm2 start server.py --interpreter python3 --name Deteksi-lahan
